1). Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array


In [12]:
import numpy as np

a = np.array([1, 2, 3])
print(a)


[1 2 3]


2). Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10


In [21]:
a1 = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])

print(a1)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3). Write a NumPy program to append values at the end of an array


In [45]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])

new_r = np.array([7, 8, 9])

print(np.append(a2, [new_r], axis=0))

print()

a3 = np.array([[1, 2], [4, 5], [7, 8]])

new_c = np.array([3, 6, 9])

new_c = new_c.reshape(-1, 1)

print(np.append(a3, new_c, axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
