<h4 style="color: blue;">Pra-2). Write a NumPy program</h4>


<h4 style = "color: blue;" > 1). to convert a list of numeric values into a one-dimensional NumPy array</h4>


In [3]:
import numpy as np

a = np.array([1, 2, 3])
print(a)


[1 2 3]


<h4 style="color: blue;">
2). to create a 3x3 matrix with values ranging from 2 to 10
</h4>


In [9]:
a1 = np.array([[], [], []])
a1 = np.arange(2, 11).reshape(3, 3)
print(a1)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


<h4 style="color: blue;">3). to append values at the end of an array</h4>


In [ ]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])

new_r = np.array([7, 8, 9])

print(np.append(a2, [new_r], axis=0))

print()

a3 = np.array([[1, 2], [4, 5], [7, 8]])

new_c = np.array([3, 6, 9])

new_c = new_c.reshape(-1, 1)

print(np.append(a3, new_c, axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<h4 style="color: blue;">4).to create another shape from an array without changing its data(3*2 to 2*3)</h4>


In [7]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

arr = arr.T

print(arr)


[[1 3 5]
 [2 4 6]]
